import {useEffect} from "react"
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Modal, CircularProgress } from "@mui/material"
import { useDispatch, useSelector } from 'react-redux';
import { getAllMostEmailed, getAllMostShared, getAllMostViewed } from "../services/api"
import { ApplicationState } from "../services/reducers"
import BasicTabs from "../components/tabs"

const Home: NextPage = () => {
    const dispatch = useDispatch();
    const viewed = useSelector((state: ApplicationState) => state.viewedReducer);
    const shared = useSelector((state: ApplicationState) => state.sharedReducer);
    const emailed = useSelector((state: ApplicationState) => state.emailedReducer);
    // const useTypeDispatch:()=>AppDispatch = useDispatch
    useEffect(() => {
        dispatch(getAllMostViewed(1));
        dispatch(getAllMostEmailed(7));
        dispatch(getAllMostShared(30));
    }, []);
  return viewed.loading ? (
    <div className={styles.container}>
      <Head>
        <title>New York Times Most Popular</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          New York Times Most Popular
        </h1>
        <BasicTabs viewed={viewed} shared={shared} emailed={emailed}/>
      </main>
    </div>
  ) : (
      <CircularProgress sx={{
        position : 'absolute',
        top : '50%',
        left : '50%',
        transform : 'translate(-50%, -50%)'
      }}/>
  )
}

export default Home
